// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADIz2ERQZp5DVsjp61qR4nyFkFhmyi9cw',
    appId: '1:573953676915:web:27b16446cde9f81bd8bc06',
    messagingSenderId: '573953676915',
    projectId: 'flutter-user-34254',
    authDomain: 'flutter-user-34254.firebaseapp.com',
    storageBucket: 'flutter-user-34254.appspot.com',
    measurementId: 'G-Z0W92ZVM8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOG1VC_dbNs8eFqJCOBu5Wzn2EtH0HfNU',
    appId: '1:573953676915:android:c9e1632b1a2f0ef4d8bc06',
    messagingSenderId: '573953676915',
    projectId: 'flutter-user-34254',
    storageBucket: 'flutter-user-34254.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCav7xW04FTfAMy6_6xYQ937Xep213Zlsk',
    appId: '1:573953676915:ios:5fd103b1770fb609d8bc06',
    messagingSenderId: '573953676915',
    projectId: 'flutter-user-34254',
    storageBucket: 'flutter-user-34254.appspot.com',
    iosClientId: '573953676915-lhtkofttc0k4asq57h7crtqptg3vil7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFluter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCav7xW04FTfAMy6_6xYQ937Xep213Zlsk',
    appId: '1:573953676915:ios:728cc68ba1a6772ad8bc06',
    messagingSenderId: '573953676915',
    projectId: 'flutter-user-34254',
    storageBucket: 'flutter-user-34254.appspot.com',
    iosClientId: '573953676915-gqn99qk21hn5kmkh1ulbhi4s628iav0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFluter.RunnerTests',
  );
}
